"""inicial

Revision ID: 862a4f3e670f
Revises: 
Create Date: 2021-03-26 03:38:48.341402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862a4f3e670f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(length=60), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('bairro', sa.String(length=45), nullable=False),
    sa.Column('cidade', sa.String(length=45), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('raca', sa.String(length=45), nullable=False),
    sa.Column('porte', sa.String(length=10), nullable=False),
    sa.Column('genero', sa.String(length=1), nullable=False),
    sa.Column('especie', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=False),
    sa.Column('telefone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.ForeignKeyConstraint(['telefone_id'], ['telefones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('pets_has_clientes',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('cliente_id', 'pet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets_has_clientes')
    op.drop_table('clientes')
    op.drop_table('telefones')
    op.drop_table('pets')
    op.drop_table('enderecos')
    # ### end Alembic commands ###
